### ISSUE TITLE
Render Rmd for non-episode files

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/sandpaper#172]
With `styles` only Rmd files in the `_episodes_rmd` folder were knitted.
Does/Could {sandpaper} support rendering Rmd files anywhere? (e.g., in the `leaner/` or `instructor/` folders as suggested [here](https://github.com/carpentries/styles/issues/619))

**Comment by zkamvar** [comment]
Yes, we do support rendering Rmd files anywhere. 

The reason is because all source files are discovered through [`get_resource_list()`](https://github.com/carpentries/sandpaper/blob/1f89d5dd939f8813681ad886637261843cd53584/R/utils-paths-source.R#L28-L42) and all Markdown and R Markdown sources are subsequently passed through this function that will render R Markdown sources or simply copy plain Markdown sources:

https://github.com/carpentries/sandpaper/blob/1f89d5dd939f8813681ad886637261843cd53584/R/utils-callr.R#L1-L60
