### ISSUE TITLE
Add a Lesson Credit page

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#238]
A page to list the contributors to a lesson, the Maintainers, supporting institutions/funding bodies, etc. The exact nature of this is likely to be heavily informed by discussions in [the Lesson Publication Task Force](https://carpentries.org/blog/2021/10/lesson-publication-task-force/).

**Comment by zkamvar** [comment]
Thinking about this particular issue and the reason why I haven't yet started on it is due to scope:

The scope for the Lesson Publication Task Force:
 - time-bound: this happens for each lesson release cycle
 - maintainers and authors only (funders/institutions are not considered in this)
 - deployed to Zenodo for archiving

The scope for this page:
 - dynamic (this is updated as the lesson grows)
 - maintainers, authors, contributors, and funders/institutions
 - remains editable and portable with the lesson

I think the thing I keep getting stuck on is the fact that we don't have a single way to credit authors dynamically. The LPTF has recommended solutions that rely heavily on processes that have not yet been set up and require extra development time to do so. Moreover, because the authors are needed for the lesson release, we need to make sure that we do not duplicate effort for the maintainers to maintain an author list in more than one place.

One solution I'm thinking of is to create a function that will auto-generate the author list from a well-defined author list mechanism (e.g. a cff file, an all-contributors config file, a DESCRIPTION file, and whatever we come up with for the LPTF) and use that to insert the author list in the lesson itself.

**Comment by apirogov** [comment]
Just FYI, in CFF (see mentioned issue) there are already plans for granular contributor roles for the next version of the format. Possibly of interest in this context:

https://github.com/citation-file-format/citation-file-format/issues/112#issuecomment-1610851858

**Comment by tobyhodges** [comment]
Thanks @apirogov, very much so. In fact, and inspired by the issue you opened on carpentries/workbench, I was browsing exactly that discussion on the CFF repo yesterday. Support for contributor roles in CFF would probably remove one of the biggest headaches we have at the moment: how to distinguish (in a maachine-readable way) lesson maintainers and reviewers from everyone else who should be listed as an author?

**Comment by ErinBecker** [comment]
Closed with https://github.com/carpentries/varnish/pull/122
