### ISSUE TITLE
Add anchors to section and box (callout etc.) titles

### ISSUE THREAD

**Issue by fiveop** [carpentries/sandpaper#285]
In the old template there are anchors, visibly represented by two chain links, next to sections and box titles, that are links to those titles and thus allow to copy them.

In the new template there are IDs on the appropriate elements, so one can construct such links by looking in the source, but there are no visible links to use for people that do not want or know how to do that.

**Comment by zkamvar** [comment]
I have not yet included these in part because I want to make sure they are accessible for screen readers (see this [in-depth post about anchor links from 2020](https://amberwilson.co.uk/blog/are-your-anchor-links-accessible) for details).

This could be implemented with an external JS library, but because I would like to avoid CDN content as much as possible, I'm going to move this issue over to {sandpaper} so that we can implement it in the markdown -> HTML conversion process.

**Comment by zkamvar** [comment]
This has been fixed in #325
