### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by Athanasiamo** [carpentries/sandpaper#301]
The search feature doesnt seem to be working (I'm on chrome). 
I cant get my cursor to land in the search field or get to typing anything.

I've tried both on locally rendered pages and GHA rendered pages.

**Comment by zkamvar** [comment]
Thank you for bringing this up!

I've disabled the search purposefully in [varnish 0.1.15](https://carpentries.github.io/varnish/news/index.html#varnish-0115) because I need to take some time to implement a proper solution that is accessible. 

I'm going to close this in favour of https://github.com/carpentries/workbench/issues/8, which has more details about why the search has been disabled. 

(note: github only gives me two choices of closing: "completed" or "not planned", I want to emphasize that this IS planned, but the [Workbench Beta phase](https://carpentries.org/blog/2022/06/dovetail-003/#upcoming-and-current-lessons-in-workbench-beta) is the current priority, which will certainly become easier to handle in the next couple of months)
