### ISSUE TITLE
Flag code blocks if they are expected to fail

### ISSUE THREAD

**Issue by dpshelio** [carpentries/sandpaper#305]
It would be good to be able to mark code blocks with something if they are expected to throw an error. Then the CI could fail if other blocks rather than the ones marked have produced any error. Similarly to unit-test frameworks where you can mark tests that should fail.

**Comment by zkamvar** [comment]
I think this is a good idea.

The flag in question is `error = TRUE` (see https://yihui.org/knitr/options/#text-output) and it's `TRUE` by default in knitr. I would recommend to flag those chunks with `error = TRUE` at the moment and I will work a solution around that.

My only concern right now is that we have several R lessons that use errors as examples, but no one is using this flag because it's been enabled by default for our lessons since 2018.

## Quick solution

I implement a `config.yaml` option that's called something like `fail_on_error: true`, so if it's present, then we will add `error = FALSE` into the default chunk options:

https://github.com/carpentries/sandpaper/blob/1c018b2035c203a89f1cd5356e1be41345d90c2e/R/utils-callr.R#L30-L38

This way, your build will fail if a chunk produces an error that is unexpected.

## Longer term solution

One of the benefits of having `error = TRUE` by default is that we can see all of the errors at once instead of failing on the first error.

What I propose is that I implement a post-rendering check for errors (via {pegboard}) and report them as warnings to the author/CI unless they are generated from a chunk that has `error = TRUE`.
