### ISSUE TITLE
Feature request: create_episode could insert as well as append

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#330]
Especially in the early stages of lesson design and development, it can be necessary to add a new episode (or split an existing episode) in the middle of the lesson. This can be a bit of a faff to handle, particularly if using numbered episode files (e.g. `05-schism.md`), as you have to rename every episode after the new one you are inserting.

`create_episode` initialises a new episode file and appends it to the current list of episodes based on the numbers already present in their filenames. If it is possible, it would be very helpful to have an option to specify that the function should insert the new episode somewhere else in the lesson, automatically shifting incrementing the numbers in the names of other episode files to accommodate the insertion.

**Comment by zkamvar** [comment]
This was my fault for making a numbered episode system the default in the first place 😞. When I wrote {sandpaper}, I was hoping we would move away from the numbered episode system and rely on the episode order being defined in `config.yaml`, but instead I've reinforced the number system and made it more complicated. 

## Inserting an episode

I think having a parameter to insert the episode in a specified position makes sense. We could override the `add` parameter to do something like:

```r
create_episode("Being Mindful About Defaults", add = FALSE) # Does not add to the index
create_episode("Being Mindful About Defaults", add = TRUE) # adds to the end of the index
create_episode("Being Mindful About Defaults", add = 4) # adds to position number 4, renames other episodes if necessary
```

That being said, if we are going to rename episodes, I would be much happier removing the prefix all together because of caveats I list below in challenges.

## Renaming episodes

Renaming episodes depends on if the episodes have sequential names in the first place.
One thing that we could do is to provide a function that will strip off the episode prefixes and ensure that the correct order gets recorded in the `config.yaml`.

```r
get_episodes()
#> [1] 01-introduction.Rmd [...] 10-final-episode.Rmd
strip_episode_prefix(write = TRUE)
#> 10 episodes had prefix stripped
get_episodes()
#> [1] introduction.Rmd [...] final-episode.Rmd
```

If we have this, episodes would only need to be renamed once as opposed to the insert and rename strategy where you would have to rename episodes almost every time you insert an episode (barring inserting an episode at the end).

### Challenges

The biggest challenges come from invalid links. These could be handled for website users by [making explicit redirects](https://pkgdown.r-lib.org/reference/build_site.html#redirects), but this gets more complex if we have the situation where we are doing multiple passes of renaming numbered episodes (e.g. `05-functions.Rmd` is renamed to `06-functions.Rmd` and then `07-functions.Rmd`).

There is still the matter of internal links being changed. The good thing is that these links would be detected by {pegboard}, the bad thing is that there are still some corner cases for rewriting a markdown file with pegboard that make me uneasy to implement the automated fix right away. Luckily, if {sandpaper} renames episodes to strip off the numbered component, this action would only need to be performed once.

**Comment by zkamvar** [comment]
It should be noted that [`create_episode(..., make_prefix = FALSE)`](https://carpentries.github.io/sandpaper/reference/create_episode.html) will create an episode without a prefix

**Comment by tobyhodges** [comment]
Do you think it is now too late to change the default for `make_prefix` to `FALSE` in `create_episode`, and to remove the prefix from the boilerplate `introduction` file?

**Comment by tobyhodges** [comment]
I also wonder how well `git` will cope with the episode renaming, if done by `create_episode`.

**Comment by zkamvar** [comment]
> Do you think it is now too late to change the default for `make_prefix` to `FALSE` in `create_episode`, and to remove the prefix from the boilerplate `introduction` file?

I do not think now is too late. It is indeed the best time to do this. 

> I also wonder how well `git` will cope with the episode renaming, if done by `create_episode`.

I'm not sure I follow. How do you mean?

**Comment by zkamvar** [comment]
This is going to take a bit to implement as it breaks 69 tests, but I have laid out a path forward for the behaviour in #333

**Comment by tobyhodges** [comment]
> > I also wonder how well git will cope with the episode renaming, if done by create_episode.
> 
> I'm not sure I follow. How do you mean?

When I rename a file, I usually try to do it by `git mv`, so that Git recognises that the file has been renamed, rather than deleted and a new file created. I'm not sure how easy it will be to record these file renamings in the version history of the project. But I admit I haven't tested, so may be worrying unduly.

**Comment by zkamvar** [comment]
> When I rename a file, I usually try to do it by `git mv`, so that Git recognises that the file has been renamed, rather than deleted and a new file created. I'm not sure how easy it will be to record these file renamings in the version history of the project. But I admit I haven't tested, so may be worrying unduly.

Ah, I see! I myself have never used `git mv` and what I see is that the unstaged files appear to be a deletion and addition, but upon staging, they are recognised as a rename.

**Comment by zkamvar** [comment]
Hi Toby, I believe sandpaper version 0.10.0 addresses this issue, but since there are caveats to it (no renaming of episodes in a numeric context), I would like for you to determine if this can be closed.

**Comment by tobyhodges** [comment]
As the default behaviour has been changed and `move_episode` can be used to reorganise episodes, this has been addressed to my satisfaction, thanks @zkamvar.
