### ISSUE TITLE
Templates for Episode Snippets

### ISSUE THREAD

**Issue by fiveop** [carpentries/sandpaper#368]
Is it possible to create and then include parameterized templates in episodes?

I could not find anything in the documentation of sandpaper and the page on workbench as a whole.

**Comment by zkamvar** [comment]
Hi @fiveop,

Can you describe your use case? If you are using R Markdown, you should be able to [use child documents](https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html) to create modular chunks of markdown or R Markdown that you can spread across episodes. Otherwise, I think this is related to #81.

Please note that I may not be able to respond until after 28 November.

**Comment by ocaisa** [comment]
@fiveop Next year we are planning to move HPC intro to the new lesson framework, can you point me to what you are working on so we can keep an eye on how you implement this.

**Comment by fiveop** [comment]
@ocaisa I intend to use it to provide two versions of https://github.com/carpentries-incubator/gitlab-novice (web interface only vs. local repository/GitLab interaction). I started to work on that in the `gitless` branch and I will continue to work on this till at least early February, when I am going to give the course again.

However, I would prefer a solution/a tool that is explicitly intended for multiple versions (see #367 ).

**Comment by fiveop** [comment]
I am currently trying to use child documents. It was a bit tricky to get it to work and that might be, because I miss something. The build process is looking for child documents under `/home/runner/work/<reponame>/<reponame>/site/built/`. Files seem to get there by checking out the branch `md-outputs`, which was filled by the previous built. And only certain files seem to be put there (Those from /, /episodes/, /instructors/, /learners/, and /profiles/). I initially tried to place the child documents in `/episodes/snippets/` but those were not placed in `md-outputs`.

I included the snippets with:

````
```{r, child=c('markdown-lists.md')}
```
````
(When I tried to place the snippets in `/episodes/snippets/` that was `…c('episodes/snippets/markdown-lists.md')…`)

So I have two issues with this:
1. How can I access markdown files that were not built/copied by the previous run?
2. How can I place them in other places than root (or one of the other directories mentioned above)?

**Comment by zkamvar** [comment]
Hi @fiveop,

I'm so sorry I did not get to this sooner. I've been out sick taking care of a family member. 

In short, a quick solution is to move `snippets` to `files/snippets` and update the child directive for that. I will update the sandpaper settings to allow for a subfolder called "snippets" and then I will make a more generalised method of including these soon. 

## Details

The build process is a two-step process during which the source documents are rendered into `site/built` and then HTML sent to `site/docs` (though I've been meaning to change the name of that last one), which is described [in the workflow guide](https://carpentries.github.io/workbench/workflow-guide.html#local-workflow).

To avoid detritus from building up in the source folder, the Rmd -> md process takes place within the `site/built` folder. Before building episodes, sandpaper will copy all file assets inside of `episodes/`, but only the `files/`, `fig/` and `data/` folders to `site/built` as shown here: 

https://github.com/carpentries/sandpaper/blob/796f0b07333b504f028a8c2385d4b1c0b1064d0f/R/build_markdown.R#L66-L76

Note that `get_artifacts()` will search for any `Rmd` or `md` files in the top level of `episodes/`.

The decision to include only those folders was to map the common folders from the original template and avoid proliferation of additional folders under `episodes/` that would lead to a situation where lessons would be built in _slightly_ different ways. 

[The remote workflow](https://carpentries.github.io/workbench/workflow-guide.html#remote-workflow) is the same as the local workflow, except those folders are mapped to orphan branches use `git worktree`, which is why you see the `site/built` folder mapping to `md-outputs`.

**Comment by trhallam** [comment]
Perhaps a bit late to the show here. But I migrated the EPCC version of the HPC carpentry to the Workbench last year.

Child documents are better for larger amounts of text, but I found a need for a more modular set of active parameters similar to Jinja templating which was extensively used by the old HPC carpentry.

My solution was to write a YAML file for parameters which is then loaded at the top of each Rmd. This example includes child document snippets as well.

`lesson_config.yaml`
```yaml
---
snippets: EPCC_ARCHER2_slurm

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/bin/bash"

remote:
  login: "login.archer2.ac.uk"
  location: "EPCC, The University of Edinburgh"
  user: "userid"
```

````rmd
```{r load_config, include=FALSE}
library(yaml)
config <- yaml.load_file("lesson_config.yaml")
snippets <- paste('files/snippets/', config$snippets, sep='')
```
````

Then the yaml parameters can be used in the document like so

````rmd
Go ahead and open your terminal or graphical SSH client, then log in to the
cluster using your username and the remote computer you can reach from the
outside world, `r config$remote$location`.

```bash
`r config$local$prompt` ssh `r config$remote$user`@`r config$remote$login`
```

Remember to replace ``r config$remote$user`` with your username or the one
supplied by the instructors. You may be asked for your password. Watch out: the
characters you type after the password prompt are not displayed on the screen.
Normal output will resume once you press `Enter`.
````

Its definitely less legible than Jinja but it seems to work.

[Repo](https://github.com/EPCCed/2024-06-20-hpc-intro-shampton/tree/main)
[Pages](https://epcced.github.io/2024-06-20-hpc-intro-shampton/)
