### ISSUE TITLE
the "IMPORTANT NOTE" callout obscures code boxes in some lessons 

### ISSUE THREAD

**Issue by jlahne** [carpentries/sandpaper#456]
I apologize as I am not including a reprex; I am not sure how to do so with the below issue, which is transferred from the [datacarpentry/r-socialsci](https://github.com/datacarpentry/r-socialsci) Issues page:

---

It seems like the new callout (IMPORTANT NOTE) format is interfering with the content of some code chunks.  In [line 231 of lesson 6 of the R for Social Scientists](https://github.com/datacarpentry/r-socialsci/blob/076763e1509d1594af77f451e76a55509e3ebf28/episodes/06-rmarkdown.Rmd#LL233C33-L233C33) of Episode 6 (R Markdown) there should be a setup chunk that pulls in the SAFI_clean.csv file, but in both Firefox and Safari it is obscured in the code chunk, regardless of window size (screenshot attached).

<img width="2560" alt="Screenshot 2023-05-15 at 1 19 54 PM" src="https://github.com/datacarpentry/r-socialsci/assets/48262718/39967839-a710-4c28-a1c7-bc53ec846448">

I can't figure out how to fix this (hence no pull request), as it has to do with the HTML/CSS template.

**Comment by zkamvar** [comment]
This has to do with mixing markdown and HTML in a time when it was not very easy to demonstrate a code chunk using R Markdown without it evaulating (for example, [this allowed R Markdown to pass over the chunk unevaluated](https://github.com/datacarpentry/r-socialsci/blob/076763e1509d1594af77f451e76a55509e3ebf28/episodes/06-rmarkdown.Rmd#L241-L247), see https://github.com/carpentries/lesson-transition/issues/51).


The solution is to convert those demonstrated code chunks to use [the `verbatim` code chunk engine](https://github.com/carpentries/sandpaper-docs/blob/89603e759b00b9f3dcddcbcda163ffc93419339f/episodes/episodes.Rmd#L100-L107) (using four `` ` `` characters instead of 3 for the outer fences). This way, they will render as markdown in the final output and they are easier to read in the source:


`````diff 
-<pre>
-&#96;&#96;&#96;{r setup, include = FALSE}
+````{verbatim, lang = "markdown"}
+```{r setup, include = FALSE}
library(tidyverse)
library(here)
interviews <- read_csv(here("data/SAFI_clean.csv"), na = "NULL")
+```
+````
-&#96;&#96;&#96;
-</pre>
`````

**Comment by jlahne** [comment]
Thanks, @zkamvar!  I have gone back to the original thread on datacarpentry/r-socialsci and asked if a more experienced contributor can implement the change.

**Comment by zkamvar** [comment]
Consider this was addressed in the lesson, I will close this issue as resolved.
