### ISSUE TITLE
Warning messages: In page_globals$meta : partial match of 'meta' to 'metadata'

### ISSUE THREAD

**Issue by Bisaloo** [carpentries/sandpaper#525]
I enabled warnings on partial matching by default on my computer and got these while running `sandpaper::serve()`:

> Warning messages: In page_globals$meta : partial match of 'meta' to 'metadata'

Looking at the code, it seems indeed that there are a couple of occurrence of this: 

https://github.com/search?q=repo%3Acarpentries%2Fsandpaper+%2Fpage_globals%5C%24meta%5Cb%2F&type=code

And a look at `setup_page_globals()` seems to confirm that the object it creates indeed contains a `metadata` element but no `meta` element.

https://github.com/carpentries/sandpaper/blob/043bf7df4bd9d6cf3f9d1dccd19fe4f02daadfec/R/utils-varnish.R#L110-L119

I'm opening this issue first to confirm I understood everything correctly and this is indeed what's happening. If so, I'm happy to submit a PR to not rely on partial matching and avoid potential name collisions.

**Comment by zkamvar** [comment]
This is absolutely correct! The `set_page_globals()` function will make copies of the global cache so that things like the pre-computed metadata and sidebar can be modified to suit a particular page: https://github.com/search?q=repo%3Acarpentries%2Fsandpaper%20setup_page_globals&type=code

My documentation for the global lesson elements of sandpaper is... not great I admit. 

I would be really grateful for a PR!
